
linters:
    LineLength:
        max: 120
        severity: error
    Indentation: # For consistency with default rubocop rules.
        character: space
        width: 4
        severity: error
exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'app/views/representatives/show.html.haml'
    - 'app/views/news_items/index.html.haml'
