env:
  secure: rSQy9ucAnQ1scvwlGOoDn0NCQvJAVIkZLFfKl+icltbY2lCpaQ4sNFS4gEcSUnbTzB8+NT9BCwQLrfnser6+2BL1l/EBzjdm5pmHmdQ9GKUA6gPKV+b/XZLZv8Tb3K/ICNGxlnXDQqSorhhc/8wRlofZsw6dO8Cc9gVwJiWal/1aZLGeT4WGY90OLpDmlS3wPNKxj6alLFCpYqNia5yBVSXeG/y3043npRnwX3UTEqNX9EB4XUOQcBmGZ8aN2yKzvggCdCB+3MQmlI8YZx8z8804T7xPSDZ7ClwcY3J87nRlHn2v6faIEcruDwXiVH3w26Rj+K+9Wj37hND3+Aj6S6Z9nPAR2l4WZz3oIFFS+ps76qRsPobE6msHv+M4w0VyAiTzhBc65HoRNc3wkzgJiNzqCQmAOxLApQ9TOYH7+tVRincuYRud2kOk7Wlq2aWjmuLg7ZC+CaDIhS6WKX3FYqNf4uc9SuodePylf4M5fwsHk1dVH7i/m4YquD7D7WO8ATOPEBLyXA1NI3HMR7ANzav2vA1ZazULNKqP5cH6+BhBVESxSvQvw5glMxixpN8mPwRM1PnnDP/R9c6Po36GHKRlBRgWg/cXtvwfw1SAj9W+99opfwXxEnEZNFWhzzH+KjQedwOrJA+/B77HoaRZJBU9dnMZJyMxZ5JPP9LKftU=
language: ruby
rvm:
- 2.6.5
before_install:
- nvm install 12.13.1
before_script:
- npm install -g yarn@1.22.4
- bundle config set without production
- bundle config set path vendor/bundle
- bundle install
- yarn install
script:
- bundle exec rake db:drop
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec cucumber
- bundle exec rspec
